name: Tests for dispatch
on: 
  push:
    branches: [ main ]
  pull_request: {}
jobs:
  test:
    strategy:
      matrix:
        operating-system: [ macos-latest ]
        ocaml-version: [ 4.12.0 ]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pinning Package
      run: opam pin add -yn dispatch.dev './'
    - name: Packages
      run: opam depext -yt dispatch.dev
    - name: Dependencies
      run: opam install -t -y . --deps-only
    - name: Building, Installing and Testing
      run: opam exec -- dune build @install @runtest